import 'package:fast_app_base/common/common.dart';
import 'package:fast_app_base/screen/main/tab/stock/wo_stock.dart';

List<Stock> myInterestStocks = [
  Stock(stockName: '한화솔루션',
      stockImagePath: '$basePath/stock/interest_stock_01.png',
      currentPrice: 41600,
      yesterdayClosePrice: 41600),
  Stock(stockName: '현대모비스',
      stockImagePath: '$basePath/stock/interest_stock_02.png',
      currentPrice: 219000,
      yesterdayClosePrice: 217000),
  Stock(stockName: '셀트리온',
      stockImagePath: '$basePath/stock/interest_stock_03.png',
      currentPrice: 78000,
      yesterdayClosePrice: 8000),
  Stock(stockName: '주식4',
      stockImagePath: '$basePath/stock/interest_stock_04.png',
      currentPrice: 50000,
      yesterdayClosePrice: 50000),
  Stock(stockName: '주식 5',
      stockImagePath: '$basePath/stock/interest_stock_05.png',
      currentPrice: 41500,
      yesterdayClosePrice: 41600),
  Stock(stockName: '주식 6',
      stockImagePath: '$basePath/stock/interest_stock_06.png',
      currentPrice: 41600,
      yesterdayClosePrice: 41600),
  Stock(stockName: '주식 7',
      stockImagePath: '$basePath/stock/interest_stock_07.png',
      currentPrice: 41600,
      yesterdayClosePrice: 41600),
  Stock(stockName: '주식 8',
      stockImagePath: '$basePath/stock/interest_stock_08.png',
      currentPrice: 41600,
      yesterdayClosePrice: 41600),
  Stock(stockName: '주식 9',
      stockImagePath: '$basePath/stock/interest_stock_09.png',
      currentPrice: 41600,
      yesterdayClosePrice: 41400),
  Stock(stockName: '주식 10',
      stockImagePath: '$basePath/stock/interest_stock_10.png',
      currentPrice: 44600,
      yesterdayClosePrice: 51600),
  Stock(stockName: '주식 11',
      stockImagePath: '$basePath/stock/interest_stock_11.png',
      currentPrice: 41600,
      yesterdayClosePrice: 41600),
];